[package]
name = "far-memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuzzyhash = "0.2.1"
indicatif = "0.17.3"
rdkafka = "0.29.0"
tokio = { version = "1.24.2", features = ["full"] }
serde = "1.0.152"
serde_json = "1.0.91"
rand = "0.8.5"
csv = "1.1.6"
toml = "0.5.11"