[package]
name = "far-memory"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tonic = "0.9.2"
prost = "0.11.9"
vblk = "0.1.2"
toml = "0.7.6"
serde = { version = "1.0.179", features = ["derive"] }
bincode = "1.3.3"
lru = "0.11.0"

[build-dependencies]
tonic-build = "0.9.2"