[package]
name = "far-memory"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tonic = "0.9.2"
prost = "0.11.9"
vblk = "0.1.2"

[build-dependencies]
tonic-build = "0.9.2"