apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: far-memory-storage
  namespace: default
spec:
  selector:
    matchLabels:
      app: far-memory-storage
  replicas: 1
  serviceName: far-memory-storage
  template:
    metadata:
      labels:
        app: far-memory-storage
    spec:
      containers:
      - name: far-memory-storage
        image: ghcr.io/nikitavbv/far-memory/far-memory:0.1.28
        env:
        - name: FAR_MEMORY_CONFIG
          value: /etc/far-memory/config/config.toml
        volumeMounts:
        - name: config
          mountPath: /etc/far-memory/config
      volumes:
      - name: config
        configMap:
          name: far-memory-config
          items:
          - key: config.toml
            path: config.toml
---
apiVersion: v1
kind: Service
metadata:
  name: far-memory-storage
  namespace: default
spec:
  selector:
    app: far-memory-storage
  ports:
  - port: 9000
    targetPort: 9000