on: [push]

name: Continuous integration

jobs:
  server-build:
    name: server build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v2
    - uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        file: infrastructure/docker/Dockerfile
        context: '.'
        push: true
        tags: |
          ghcr.io/nikitavbv/far-memory/far-memory:latest
          ghcr.io/nikitavbv/far-memory/far-memory:0.1.${{ github.run_number }}

  thesis:
    name: compile thesis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wtfjoke/setup-tectonic@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: tectonic thesis/thesis.tex --outfmt pdf
    - uses: actions/upload-artifact@v3
      with:
        name: thesis
        path: thesis/thesis.pdf